{
 "title": "DSN General",
 "time": { "from": "2025-05-27T04:51:43.364Z", "to": "2025-07-17T18:19:24.428Z" },
 "templating": {
  "list": [
   { "name": "stations", "label": "Stations", "query": "cdscc, mdscc, gdscc" },
   {
    "name": "dishes",
    "label": "Dishes",
    "query": {
     "query": "label_values({station_name=~\"$stations\"},dish_name)"
    }
   },
   { "name": "targets", "label": "Targets", "query": { "query": "label_values(target_name)" } },
   {
    "name": "metrics",
    "label": "Metrics",
    "query": {
     "query": "metrics((dish|target|signal).*)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Meta Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Periods of Missing Data",
     "type": "state-timeline",
     "description": "Periods during which no data was received for signals.\nAnnotations provide reasons if not due to DSN engineering.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "absent(dish_array_bool)", "legendFormat": "__auto" },
      {
       "expr": "absent(signal_data_rate_b_per_s) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
     "options": {
      "content": "# Variable Guide\nThe advice given here applies to all dashboards.\n\nMetrics:\n- Selects metrics for the exploration section\n\nStations: \n- Set the Deep Space Communication Complex\n- Important when looking at wind speed, elevation and azimuth \n- Remember that CDSCC is in the southern hemisphere\n\nDishes:\n- The selectable values depend on the stations variable.\n\nTargets:\n- Consult the DSN Targets dashboard for long names.\n- Exclude VGR1, VGR2, JNO and NHPC for distance related visualizations to get a better view of the closer spacecraft.\n\n\n"
     }
    },
    { "title": "Dashboard Overview", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 } }
   ]
  },
  {
   "title": "Exploring the Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "# Usage\nThe graphs of this section depend on the metrics variable.\n\nPlease select the metric you want to plot using the variable selector.\n\nSince some metrics do not contain target names, the filter does not effect the visualization of this section.\n\nThe metric on the horizontal axis of the Metric Explorer panel has to set manually in the panel configuration.\n\n"
     }
    },
    {
     "title": "$metrics CDF",
     "type": "sebastiangunreben-cdf-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "{__name__=~\"$metrics\", station_name=~\"$stations\", dish_name=~\"$dishes\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$metrics by Dish",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "{__name__=~\"$metrics\", station_name=~\"$stations\", dish_name=~\"$dishes\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$metrics by Target",
     "type": "histogram",
     "description": "Does not work for dish metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "{__name__=~\"$metrics\", station_name=~\"$stations\", dish_name=~\"$dishes\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric Explorer",
     "type": "xychart",
     "description": "Edit the X field manually and select Y field in the legend, Not effected by variables",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "{data_source=\"DSN Now\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "General Visualizations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target Range and Position - $stations",
     "type": "grafana-xyzchart-panel",
     "description": "For Targets: $targets",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sin((dish_azimuth_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\"} != 180 != 360 != 120 != 0) * 3.1415 / 180) * on(dish_name,dish_activity) group_right() (target_range_km{data_source=\"DSN Now\", target_name=~\"$targets\", station_name=~\"$stations\", dish_name=~\"$dishes\"} > 0)  * on(dish_name, dish_activity) group_left cos((dish_elevation_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\"} != 90 != 88 > 5) * 3.1415 / 180)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(target_range_km{data_source=\"DSN Now\", target_name=~\"$targets\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"} > 0)  * on(dish_name, dish_activity) group_left() sin((dish_elevation_angle_degrees  != 90 > 5) * 3.1415 / 180) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "cos((dish_azimuth_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\"}!= 180 != 360 != 0 != 120) * 3.1415 / 180) * on(dish_name,dish_activity) group_right() (target_range_km{data_source=\"DSN Now\", target_name=~\"$targets\", dish_name=~\"$dishes\", station_name=~\"$stations\"} > 0)  * on(dish_name, dish_activity) group_left cos((dish_elevation_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\"} != 90 != 88 > 5) * 3.1415 / 180)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logarithmic Data Rate CDF",
     "type": "sebastiangunreben-cdf-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "log10(signal_data_rate_b_per_s > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Power Received CDF",
     "type": "sebastiangunreben-cdf-panel",
     "description": "Only accounting for power higher than -200 dBm",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "signal_power_received_dBm > -200\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Contact Plans",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 4 },
     "options": {
      "content": "# Guide: How to export a contact plan\n## Step 1: Download data\n- Select dishes and targets using the variable selectors\n- Set time span using the time picker\n- Check availability of data using \"Contact Plan Data\" panel\n- Select the three dots menu in the upper right corner of the \"Contact Plan Data\" panel\n- Select \"Inspect\" and thereafter \"Data\"\n- Expand the data options line by clicking on the arrow head\n- Check the \"Apply panel transformations\" box\n- Press the \"Download CSV\" button  \n\n## Step 2: Convert to contact plan format\n- Call the contact.py command line utility on the downloaded file\n- For usage help see: \n```\npython contact.py -h\n```\n- Example:\n```\npython contact.py downloaded_contact_plan_data.csv --format HDTN\n```\n"
     }
    },
    {
     "title": "Contact Plan Data",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "signal_data_rate_b_per_s{station_name=~\"$stations\", target_name=~\"$targets\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\",signal_activity=\"true\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "target_range_km{data_source=~\"DSN Now\", station_name=~\"$stations\", target_name=~\"$targets\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "target_range_km{data_source=~\"SPICE\", station_name=~\"$stations\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}