{
 "title": "DSN Stations",
 "time": { "from": "2025-05-27T08:27:38.585Z", "to": "2025-07-17T11:12:31.715Z" },
 "templating": {
  "list": [
   { "name": "stations", "label": "Stations", "query": { "query": "label_values(station_name)" } },
   {
    "name": "dishes",
    "label": "Dishes",
    "query": {
     "query": "label_values({station_name=~\"$stations\"},dish_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dish Availability and Activities",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_name, dish_activity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dish Signal Availability",
     "type": "state-timeline",
     "description": "Green: signal active,\nOrange: signal inactive,\nRed: no signal",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "signal_data_rate_b_per_s{station_name=~\"$stations\", dish_name=~\"$dishes\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Downlink Signals per Dish",
     "type": "state-timeline",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "count(signal_data_rate_b_per_s{signal_direction=\"down\", station_name=~\"$stations\", dish_name=~\"$dishes\", signal_activity=\"true\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"}) by (dish_name)\nor (group(dish_array_bool) by (dish_name) - 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Concurrent Downlink Signals",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "count(signal_data_rate_b_per_s{signal_direction=\"down\", station_name=~\"$stations\", dish_name=~\"$dishes\", signal_activity=\"true\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"}) by (station_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Count of Dish Activities",
     "type": "timeseries",
     "description": "Micro gaps appear due to cut off in visualization",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "count(dish_azimuth_angle_degrees{station_name=~\"$stations\",dish_name=~\"$dishes\"}) by (dish_activity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dish Activity Proportions",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(label_join(count(dish_wind_speed_km_per_h{dish_name=~\"$dishes\", station_name=~\"$stations\"}) by (dish_activity, dish_name, station_name), \"ground\", \"_\" , \"station_name\", \"dish_name\")[$__interval:5s])\nor \nsum_over_time(label_replace(count(dish_wind_speed_km_per_h{station_name=~\"$stations\"}) by (dish_activity, station_name), \"ground\", \"$1\" , \"station_name\", \"(.*)\")[$__interval:5s])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wind Speed",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "targets": [
      {
       "expr": "sum without (dish_name) (label_replace(avg(dish_wind_speed_km_per_h{dish_name=~\"$dishes\", station_name=~\"$stations\"} > 0) by (dish_name), \"ground\", \"$1\" , \"dish_name\", \"(.*)\"))\nor\nsum without (station_name) (label_replace(avg(dish_wind_speed_km_per_h{dish_name=~\"$dishes\", station_name=~\"$stations\"} > 0) by (station_name), \"ground\", \"$1\" , \"station_name\", \"(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed per Dish - $stations",
     "type": "sebastiangunreben-cdf-panel",
     "description": "\n",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "repeat": "stations",
     "targets": [
      {
       "expr": "avg(dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"} == dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed per Dish Activity - $stations",
     "type": "histogram",
     "description": "\n",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
     "repeat": "stations",
     "targets": [
      {
       "expr": "avg(dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"} == dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_activity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed per Dish Activity - $stations",
     "type": "histogram",
     "description": "\n",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
     "repeat": "stations",
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "targets": [
      {
       "expr": "avg(dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"} == dish_wind_speed_km_per_h{station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_activity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed & Elevation",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "dish_elevation_angle_degrees{dish_name=~\"$dishes\", station_name=~\"$stations\"} >= 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "dish_wind_speed_km_per_h{dish_name=~\"$dishes\", station_name=~\"$stations\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wind Speed & Azimuth",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "dish_azimuth_angle_degrees{dish_name=~\"$dishes\", station_name=~\"$stations\"} > 0 != 180 ",
       "legendFormat": "__auto"
      },
      {
       "expr": "dish_wind_speed_km_per_h{dish_name=~\"$dishes\", station_name=~\"$stations\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Angles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dish Azimuth Angle per Activity - $stations",
     "type": "sebastiangunreben-cdf-panel",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 334 },
     "repeat": "stations",
     "targets": [
      {
       "expr": "avg(dish_azimuth_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_activity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dish Elevation Angle per Activity - $stations",
     "type": "sebastiangunreben-cdf-panel",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 334 },
     "repeat": "stations",
     "targets": [
      {
       "expr": "avg(dish_elevation_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_activity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dish Azimuth Angle per Dish - $stations",
     "type": "sebastiangunreben-cdf-panel",
     "description": "Only for dish activity \"Spacecraft Telemetry, Tracking, and Command\"",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 364 },
     "repeat": "stations",
     "targets": [
      {
       "expr": "avg(dish_azimuth_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"}) by (dish_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dish Elevation Angle per Dish - $stations",
     "type": "sebastiangunreben-cdf-panel",
     "description": "Only for dish activity \"Spacecraft Telemetry, Tracking, and Command\"",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 374 },
     "repeat": "stations",
     "targets": [
      {
       "expr": "avg(dish_elevation_angle_degrees{station_name=~\"$stations\", dish_name=~\"$dishes\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"}) by (dish_name)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data rate per Dish Direction - $stations",
     "type": "xychart",
     "description": "Size: Data Rate,\nColor: Target ID",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 385 },
     "targets": [
      {
       "expr": "dish_azimuth_angle_degrees{station_name=~\"$stations\",dish_name=~\"$dishes\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"} + on(dish_name,  dish_activity) group_right(target_id) (signal_data_rate_b_per_s * 0) != 180",
       "legendFormat": "__auto"
      },
      {
       "expr": "dish_elevation_angle_degrees{station_name=~\"$stations\",dish_name=~\"$dishes\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\"} + on(dish_name,  dish_activity) group_right(target_id) (signal_data_rate_b_per_s * 0) != 90 != 88",
       "legendFormat": "__auto"
      },
      {
       "expr": "signal_data_rate_b_per_s{station_name=~\"$stations\",dish_name=~\"$dishes\", dish_activity=\"Spacecraft Telemetry, Tracking, and Command\", signal_activity=\"true\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Network Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 401 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(signal_data_rate_b_per_s{dish_activity=\"Spacecraft Telemetry, Tracking, and Command\", signal_activity=\"true\", station_name=~\"$stations\", dish_name=~\"$dishes\"}) by (dish_name)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data Rate per Dish",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 410 },
     "targets": [
      {
       "expr": "sum(signal_data_rate_b_per_s{station_name=~\"$stations\", dish_name=~\"$dishes\", signal_activity=\"true\"}) by (dish_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}