{
 "title": "SOMP2B",
 "time": { "from": "2023-12-17T09:28:03.622Z", "to": "2023-12-17T09:35:48.384Z" },
 "templating": {
  "list": [
   { "name": "direction", "label": "Direction", "query": { "query": "label_values(signal_direction)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dates and Activities\n\n|Date | Activity |\n|-|-|\n|2021/05/11 | Slow download\n|2021/05/12 | Slow download\n|2023/11/04 | Command firmware update, activate payload\n|2023/11/20 | Command firmware update\n|2023/12/17 | Upload payload script\n|2023/12/19 | Fast download\n|2023/12/22 | Upload payload script\n|2023/12/23 | Upload payload script\n|2024/01/10 | Command payload, set system config\n\n\n"
   }
  },
  {
   "title": "Data Rate - $direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "direction",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(pass_transmitted_bytes_total{signal_direction=~\"$direction\"}[10s])) by (message_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pass Accumulated Data - $direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "repeat": "direction",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "last_over_time(pass_transmitted_bytes_total{signal_direction=~\"$direction\"}[1s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted Data - $direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "direction",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "last_over_time(transmitted_bytes{signal_direction=~\"$direction\"}[1s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}